before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: AAatY9iNXYCKq++zJC7liGqvB6isQmg0QuXYeaFzcvyITSDQ0H4MWcOZwG0oheG/Zp3Afi/qNfJxXUP0CNkQhMmP2Nm4Ssycwbq/hnEZkSOSsnjtPlnbNKW7u/9uIEoaLGofGQzUeppz9wUL97HrXwT6SjSwrZROb6698C/oSD/RkgtSGK0tAkO+TvMI77c0XdDjFDWI8tYrc3YfMj0glLmrW6FqHpYKYmYRFZgFQs+yZhrdmXaBPOwMcZKMbvD1eAEVPj1hHQDfUIY/3qpI3BtEBYtS0iyK3HCflARJgghJ/TgagoQfkx/hcVLE+J0rDbds4TXNHroXOFhD0H9nMQpIjyuzNmrILoFDVFjexzFV0siMJNKodkjCiv2921JHsvFkJzODmPwV4NZRhI0rXCRyppesAtl2chq2BgUwlkWzdmiKvykP+rRHeSolHQDfCG10LdnliaWhnpUJDZOasJTJHghATyEKfV1hz9GBwtTL+PDfDtYtelJxbyPfFz/TqcYH8z+zLGE9yHOYVrqP8boalqq2+vRaPX5zsNbCaesSiCzt/rGExmQxqdylZEhOHULy2X8lDqPLYX6XxYpZCRp7kO14dzdSGJHY0oYOqsuuBI19mPUZ9KvfB77Y3aCEO+bBVc9BYjKA49NM/uyKA/scJQ21IFIQ/28GAaAS+yI= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
